//
//  TermsAndConditionsPresenter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 3/16/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TermsAndConditionsPresentationLogic
{
  func presentSomething(response: TermsAndConditions.Something.Response)
}

class TermsAndConditionsPresenter: TermsAndConditionsPresentationLogic
{
  weak var viewController: TermsAndConditionsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TermsAndConditions.Something.Response)
  {
    let viewModel = TermsAndConditions.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
