//
//  SendCodeViewController.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/24/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SendCodeDisplayLogic: class
{
    func displaySomething(email:String)
    func displayReSendSuccess()
    func displayCheckSuccess()
    func displayError()
    func showLoader()
    func hideLoader()
}

class SendCodeViewController: UIViewController, SendCodeDisplayLogic
{
    var interactor: SendCodeBusinessLogic?
    var router: (NSObjectProtocol & SendCodeRoutingLogic & SendCodeDataPassing)?
    
    @IBOutlet weak var sendCodeView: UIView!
    @IBOutlet weak var codeButton: UIButton!
    @IBOutlet weak var codeTextField: UITextField!
    @IBOutlet weak var errorLabel: UILabel!
    @IBOutlet weak var bottomConstraint: NSLayoutConstraint!
    @IBOutlet weak var topConstraint: NSLayoutConstraint!
    
    var emailString: String = ""
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SendCodeInteractor()
        let presenter = SendCodePresenter()
        let router = SendCodeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
        codeButton.activationState(active: false)
        addTargetsTextField()
        hideKeyboardWhenTappedAround()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        sendCodeView.roundCorners(corners: .topRight, radius: 50)
        codeButton.roundCorners(corners:[.topLeft, .bottomLeft], radius: 20.0)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillAppear(notification:)),
                                               name: UIResponder.keyboardWillShowNotification,
                                               object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillDisappear(notification:)),
                                               name: UIResponder.keyboardWillHideNotification,
                                               object: nil)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillHideNotification , object: nil)
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    func doSomething()
    {
        interactor?.doSomething()
    }
    
    func doNewPassword()
    {
        let request = SendCode.Something.Request(email: emailString, code: codeTextField.text ?? "")
        interactor?.doNewPassword(request: request)
    }
    
    func doResend()
    {
        let request = SendCode.Something.Request(email: emailString, code: "")
        interactor?.doReSned(request: request)
    }
    
    func displaySomething(email: String)
    {
        self.emailString = email
    }
    
    func displayReSendSuccess() {
        DispatchQueue.main.async {
            self.codeTextField.text = ""
        }
    }
    
    func displayCheckSuccess() {
        DispatchQueue.main.async {
            self.router?.dataStore?.email = self.emailString
            self.router?.dataStore?.code = self.codeTextField.text ?? ""
            self.router?.routeToNewPassword()
        }
    }
    
    func displayError() {
                DispatchQueue.main.async {
                    self.errorLabel.isHidden = false
                }
    }
    
    //MARK: - Hide & Show Loader
    
    func showLoader() {
        view.showLoader()
    }
    
    func hideLoader() {
        DispatchQueue.main.async {
            self.view.removeLoader()
        }
    }
    
    @IBAction func reSendCodeButtonAction(_ sender: Any) {
        doResend()
    }
    
    @IBAction func codeButtonAction(_ sender: Any) {
        doNewPassword()
    }
    
    @IBAction func backButtonAction(_ sender: Any) {
        navigationController?.popViewController(animated: true)
    }
    
    //MARK: - Target Text Field
    
    func addTargetsTextField() {
        codeTextField.addTarget(self, action: #selector(editingChanged), for: .editingChanged)
    }
    
    @objc func editingChanged(_ textField: UITextField) {
        if textField.text?.count == 1 && textField.text?.first == " " {
            textField.text = ""
            return
        }
        guard
            let codeStr = codeTextField.text, !codeStr.isEmpty
            else {
                codeButton.activationState(active: false)
                return
        }
        codeButton.activationState(active: true)
    }
    
    //    MARK: - Keyboard Show & Hide
    @objc
    func keyboardWillAppear(notification: NSNotification?) {
        
        guard let keyboardFrame = notification?.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue else {
            return
        }
        
        let keyboardHeight: CGFloat
        if #available(iOS 11.0, *) {
            keyboardHeight = keyboardFrame.cgRectValue.height - self.view.safeAreaInsets.bottom
        } else {
            keyboardHeight = keyboardFrame.cgRectValue.height
        }
        
        let deviceModel =  UIDevice().type
        switch deviceModel {
        case  .iPhone5, .iPhone5S, .iPhone5C, .iPhoneSE:
            topConstraint.constant = 100.0
            bottomConstraint.constant = keyboardHeight + 10
        case .iPhoneX, .iPhoneXR, .iPhoneXS, .iPhoneXSMax, .iPhone11, .iPhone11Pro, .iPhone11ProMax:
            bottomConstraint.constant = keyboardHeight + 50
        default:
            bottomConstraint.constant = keyboardHeight + 10
            break
        }
    }
       
       @objc
       func keyboardWillDisappear(notification: NSNotification?) {
           let deviceModel =  UIDevice().type
           switch deviceModel {
           case  .iPhone5, .iPhone5S, .iPhone5C, .iPhoneSE:
               topConstraint.constant = 125
           default:
               break
           }
           bottomConstraint.constant = 61
       }
}

extension SendCodeViewController : UITextFieldDelegate {
    func textFieldDidBeginEditing(_ textField: UITextField) {
           errorLabel.isHidden = true
       }
}
