//
//  AccountPresenter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/24/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountPresentationLogic
{
    func presentSomething(response: Account.Something.Response)
    func presentSaveSucces()
    func presentError(error: String)
    func showLoader()
    func hideLoader()
}

class AccountPresenter: AccountPresentationLogic
{
    weak var viewController: AccountDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Account.Something.Response)
    {
        let viewModel = Account.Something.ViewModel(displeyElemnt: response.userInfo)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentSaveSucces() {
        viewController?.displaySaveSuccess()
    }
    
    func presentError(error: String) {
        viewController?.displayError()
    }
    
    func showLoader() {
        viewController?.showLoader()
    }
    func hideLoader() {
        viewController?.hideLoader()
    }
}
