//
//  AccountRouter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/24/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AccountRoutingLogic
{
    func routeToWelcome()
    func routeToSearchView()
    func routeToTermsView()
}

protocol AccountDataPassing
{
    var dataStore: AccountDataStore? { get set }
}

class AccountRouter: NSObject, AccountRoutingLogic, AccountDataPassing
{
    weak var viewController: AccountViewController?
    var dataStore: AccountDataStore?
    
    // MARK: Routing
    
    func routeToWelcome() {
        let destinationVC = Constants.Storyboards.authenticationStoryboard.instantiateViewController(withIdentifier: "WelcomeViewControllerNav") as! UINavigationController
        
        navigateToWelcome(source: viewController!, destination: destinationVC)
    }
    
    func routeToSearchView() {
        let destinationVC = Constants.Storyboards.accountStoryboard.instantiateViewController(withIdentifier: "CitySelectionViewController") as! CitySelectionViewController
        destinationVC.delegate = viewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSearchView(source: dataStore!, destination: &destinationDS)
        navigateToSearchView(source: viewController!, destination: destinationVC)
    }
    
    func routeToTermsView() {
           let destinationVC = Constants.Storyboards.accountStoryboard.instantiateViewController(withIdentifier: "TermsAndConditionsViewController") as! TermsAndConditionsViewController
           navigateToTermsView(source: viewController!, destination: destinationVC)
       }
    
    // MARK: Navigation
    
    func navigateToSearchView(source: AccountViewController, destination: CitySelectionViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToTermsView(source: AccountViewController, destination: TermsAndConditionsViewController)
    {
        source.show(destination, sender: nil)
    }
    
    
    func navigateToWelcome(source: AccountViewController, destination: UINavigationController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSearchView(source: AccountDataStore, destination: inout CitySelectionDataStore)
    {
        destination.countryId = source.countryId
        destination.searchCity = source.searchCity
    }
}
