//
//  CitySelectionPresenter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 3/1/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitySelectionPresentationLogic
{
    func presentSomething(response: CitySelection.Something.Response)
    func presetntGetCountrySuccess(countries:[Countries])
    func presetntGetCitySuccess(citys:[City])
    func presentError(error: String)
    func showLoader()
    func hideLoader()
}

class CitySelectionPresenter: CitySelectionPresentationLogic
{
    weak var viewController: CitySelectionDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CitySelection.Something.Response)
    {
        let viewModel = CitySelection.Something.ViewModel(searchCity: response.searchCity, countryId: response.countryId)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    
    func presetntGetCitySuccess(citys:[City]) {
        viewController?.displayGetCitySuccess(citys:citys)
    }
    
    func presetntGetCountrySuccess(countries:[Countries]) {
        viewController?.displayGetCountrySuccess(countries:countries)
    }
    
    func presentError(error: String) {
        viewController?.displayError()
    }
    
    func showLoader() {
        viewController?.showLoader()
    }
    func hideLoader() {
        viewController?.hideLoader()
    }
}
