//
//  CitySelectionWorker.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 3/1/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CitySelectionWorker
{
    func doGetCountryWork(page:String, userInput:String, completion: (( _ response: ResponseData) -> Void)? ) {
        NetworkManager.requestGetCountry(userInfo: ["page" : page, "userInput" : userInput], completion: completion)
    }
    
    func doGetCityWork(page:String, userInput:String, countryId:String, completion: (( _ response: ResponseData) -> Void)? ) {
        NetworkManager.requestGetCity(userInfo: ["page" : page, "userInput" : userInput, "countryId" : countryId], completion: completion)
    }
}
