//
//  SIgnInInteractor.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/21/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SIgnInBusinessLogic
{
    func doLogIn(request: SIgnIn.Something.Request)
}

protocol SIgnInDataStore
{
    //var name: String { get set }
}

class SIgnInInteractor: SIgnInBusinessLogic, SIgnInDataStore
{
    var presenter: SIgnInPresentationLogic?
    var worker: SIgnInWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doLogIn(request: SIgnIn.Something.Request)
    {
        worker = SIgnInWorker()
        presenter?.showLoader()
        _ = worker?.doLogInWork(email: request.email,
                                password: request.password,
                                completion: { response in
                                    if (response.isSuccess) {
                                        self.presenter?.hideLoader()
                                        let userToken:String = response.data?["object"] as! String
                                        Utility.saveUserToken(token: userToken)
                                        let response = SIgnIn.Something.Response()
                                        self.presenter?.presentSuccess(response: response)
                                    } else {
                                        self.presenter?.hideLoader()
                                        self.presenter?.presentError(error: response.errorForUser)
                                    }
                                    
        })
        
        
    }
}
