//
//  SIgnInWorker.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/21/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SIgnInWorker
{
    func doLogInWork(email: String , password: String, completion: (( _ response: ResponseData) -> Void)? ) {
        NetworkManager.requestLogin(userInfo: ["email":email, "password":password], completion: completion)
  }
}
