//
//  SignUpInteractor.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/21/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpBusinessLogic
{
    func doSomething(request: SignUp.Something.Request)
}

protocol SignUpDataStore
{
    //var name: String { get set }
}

class SignUpInteractor: SignUpBusinessLogic, SignUpDataStore
{
    var presenter: SignUpPresentationLogic?
    var worker: SignUpWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: SignUp.Something.Request)
    {
        worker = SignUpWorker()
        presenter?.showLoader()
        _ = worker?.doRegisterWork(email: request.email,
                                   password: request.password,
                                   isMailingSubscribe: request.isMailingSubscribe,
                                   completion: { response in
                                    if (response.isSuccess) {
                                        self.presenter?.hideLoader()
                                        let userToken:String = response.data?["object"] as! String
                                        Utility.saveUserToken(token: userToken)
                                        let response = SignUp.Something.Response()
                                        self.presenter?.presentSomething(response: response)
                                    }else {
                                        self.presenter?.hideLoader()
                                        self.presenter?.presentError(error: response.errorForUser)
                                    }
        })
    }
}
