//
//  SignUpViewController.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/21/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpDisplayLogic: class
{
    func displaySuccess(viewModel: SignUp.Something.ViewModel)
    func displayError()
    func showLoader()
    func hideLoader()
}

class SignUpViewController: UIViewController, SignUpDisplayLogic
{
    var interactor: SignUpBusinessLogic?
    var router: (NSObjectProtocol & SignUpRoutingLogic & SignUpDataPassing)?
    
    @IBOutlet weak var topConstraint: NSLayoutConstraint!
    @IBOutlet weak var signUpView: UIView!
    @IBOutlet weak var errorView: UIView!
    @IBOutlet weak var emailTextField: TitleTextField!
    @IBOutlet weak var passwordTextField: TitleTextField!
    @IBOutlet weak var reTypePasswordTextField: TitleTextField!
    @IBOutlet weak var signUpButton: UIButton!
    @IBOutlet weak var bottomConstraint: NSLayoutConstraint!
    @IBOutlet weak var signUpTopConstraint: NSLayoutConstraint!
    @IBOutlet weak var checkImage: UIImageView!
    var isMailingSubscribe: Bool = true
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SignUpInteractor()
        let presenter = SignUpPresenter()
        let router = SignUpRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        signUpButton.activationState(active: false)
        addTargetsTextField()
        hideKeyboardWhenTappedAround()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        signUpView.roundCorners(corners: .topRight, radius: 50)
        signUpButton.roundCorners(corners:[.topLeft, .bottomLeft], radius: 20.0)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillAppear(notification:)),
                                               name: UIResponder.keyboardWillShowNotification,
                                               object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillDisappear(notification:)),
                                               name: UIResponder.keyboardWillHideNotification,
                                               object: nil)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillHideNotification , object: nil)
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doRegister()
    {
        let request = SignUp.Something.Request(email: emailTextField.text ?? "", password: passwordTextField.text ?? "", isMailingSubscribe: isMailingSubscribe)
        interactor?.doSomething(request: request)
    }
    
    func displaySuccess(viewModel: SignUp.Something.ViewModel)
    {
        DispatchQueue.main.async {
            self.router?.routeToHomeTab()
        }
    }
    
    func displayError() {
        DispatchQueue.main.async {
            self.errorView.isHidden = false
            self.topConstraint.constant = 147
        }
    }
    
    //MARK: - Hide & Show Loader
    
    func showLoader() {
        view.showLoader()
    }
    
    func hideLoader() {
        DispatchQueue.main.async {
            self.view.removeLoader()
        }
    }
    
    // MARK: Actions
    @IBAction func goToSignInButtonAction(_ sender: Any) {
        router?.routeToSignIn()
    }
    
    @IBAction func checkButtonAction(_ sender: UIButton) {
        if(isMailingSubscribe == true) {
            checkImage.image = UIImage(named: "check_ic")
        } else {
            checkImage.image = UIImage(named: "unChech_ic")
        }
        isMailingSubscribe = sender.isSelected
    }
    
    @IBAction func signUbButtonAction(_ sender: Any) {
        if reTypePasswordTextField.text == passwordTextField.text {
            doRegister()
        } else {
            self.errorView.isHidden = false
            self.topConstraint.constant = 164
        }
    }
    
    @IBAction func backButtonAction(_ sender: Any) {
        navigationController?.popViewController(animated: true)
    }
    
    //MARK: - Target Text Field
    
    func addTargetsTextField() {
        emailTextField.addTarget(self, action: #selector(editingChanged), for: .editingChanged)
        passwordTextField.addTarget(self, action: #selector(editingChanged), for: .editingChanged)
        reTypePasswordTextField.addTarget(self, action: #selector(editingChanged), for: .editingChanged)
    }
    
    @objc func editingChanged(_ textField: UITextField) {
        if textField.text?.count == 1 && textField.text?.first == " " {
            textField.text = ""
            return
        }
        guard
            let passwordStr = passwordTextField.text, !passwordStr.isEmpty,
            let emailStr = emailTextField.text, !emailStr.isEmpty,
            let rePassStr = reTypePasswordTextField.text, !rePassStr.isEmpty
            
            else {
                signUpButton.activationState(active: false)
                return
        }
        signUpButton.activationState(active: true)
    }
    
    //    MARK: - Keyboard Show & Hide
    @objc
    func keyboardWillAppear(notification: NSNotification?) {
        
        guard let keyboardFrame = notification?.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue else {
            return
        }
        
        let keyboardHeight: CGFloat
        if #available(iOS 11.0, *) {
            keyboardHeight = keyboardFrame.cgRectValue.height - self.view.safeAreaInsets.bottom
        } else {
            keyboardHeight = keyboardFrame.cgRectValue.height
        }
        
        let deviceModel =  UIDevice().type
        switch deviceModel {
        case  .iPhone5, .iPhone5S, .iPhone5C, .iPhoneSE:
            signUpTopConstraint.constant = 100.0
        default:
            break
        }
        bottomConstraint.constant = keyboardHeight + 10
    }
    
    @objc
    func keyboardWillDisappear(notification: NSNotification?) {
        let deviceModel =  UIDevice().type
        switch deviceModel {
        case  .iPhone5, .iPhone5S, .iPhone5C, .iPhoneSE:
            signUpTopConstraint.constant = 125
        default:
            break
        }
        bottomConstraint.constant = 61
    }
}

//MARK: - Delegate

extension SignUpViewController : UITextFieldDelegate {
    func textFieldDidBeginEditing(_ textField: UITextField) {
        errorView.isHidden = true
        topConstraint.constant = 82
    }
}
