//
//  SignUpRouter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/21/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignUpRoutingLogic
{
    func routeToSignIn()
    func routeToHomeTab()
}

protocol SignUpDataPassing
{
    var dataStore: SignUpDataStore? { get }
}

class SignUpRouter: NSObject, SignUpRoutingLogic, SignUpDataPassing
{
    weak var viewController: SignUpViewController?
    var dataStore: SignUpDataStore?
    
    // MARK: Routing
    
    func routeToSignIn()
    {
        let destinationVC = Constants.Storyboards.authenticationStoryboard.instantiateViewController(withIdentifier: "SIgnInViewController") as! SIgnInViewController
        navigateToSignIn(source: viewController!, destination: destinationVC)
    }
    
    func routeToHomeTab()
    {
        let destinationVC = Constants.Storyboards.mainStoryboard.instantiateViewController(withIdentifier: "HomeTabBarViewController") as! HomeTabBarViewController
        navigateToMainTab(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToSignIn(source: SignUpViewController, destination: SIgnInViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToMainTab(source: SignUpViewController, destination: HomeTabBarViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: SignUpDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
