//
//  NewPasswordInteractor.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/24/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewPasswordBusinessLogic
{
    func newPassword(request: NewPassword.Something.Request)
    func doSomething()
}

protocol NewPasswordDataStore
{
    var email: String { get set }
    var code: String { get set }
}

class NewPasswordInteractor: NewPasswordBusinessLogic, NewPasswordDataStore
{
    var presenter: NewPasswordPresentationLogic?
    var worker: NewPasswordWorker?
    var email: String = ""
    var code: String = ""
    
    // MARK: Do something
    
    func newPassword(request: NewPassword.Something.Request) {
        worker = NewPasswordWorker()
        presenter?.showLoader()
        _ = worker?.doSavePasswordWorker(email: request.email,
                                         code: request.code,
                                         password: request.password,
                                         completion: { response in
                                            if (response.isSuccess) {
                                                self.presenter?.hideLoader()
                                                self.presenter?.presentSuccess()
                                            }else {
                                                self.presenter?.hideLoader()
                                                self.presenter?.presentError(error: response.errorForUser)
                                            }
        })
    }
    
    func doSomething() {
        presenter?.presentSomething(email: email, code: code)
    }
}
