//
//  NewPasswordRouter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/24/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewPasswordRoutingLogic
{
  func routeToWelcome()
}

protocol NewPasswordDataPassing
{
  var dataStore: NewPasswordDataStore? { get set }
}

class NewPasswordRouter: NSObject, NewPasswordRoutingLogic, NewPasswordDataPassing
{
  weak var viewController: NewPasswordViewController?
  var dataStore: NewPasswordDataStore?
  
  // MARK: Routing
  
  func routeToWelcome()
  {
    let destinationVC = Constants.Storyboards.authenticationStoryboard.instantiateViewController(withIdentifier: "WelcomeViewControllerNav") as! UINavigationController
      navigateToWelcome(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToWelcome(source: NewPasswordViewController, destination: UINavigationController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: NewPasswordDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
