//
//  ChatPresenter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 3/10/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatPresentationLogic
{
    func presentGetChatSuccess(chatList: [ChatInfo])
    func presentSendChatSuccess(chatItem: ChatInfo)
    func presentGetProfileSuccess(userInfo: User)
    func presentError(error: String)
    func showLoader()
    func hideLoader()
}

class ChatPresenter: ChatPresentationLogic
{
    weak var viewController: ChatDisplayLogic?
    
    // MARK: Do something
    
    func presentGetChatSuccess(chatList: [ChatInfo])
    {
        let viewModel = Chat.Something.ViewModel(chatList: chatList)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentGetProfileSuccess(userInfo: User) {
        viewController?.displeyGetUser(userInfo: userInfo)
    }
    
    func presentSendChatSuccess(chatItem: ChatInfo) {
        viewController?.displaySendSucces(chatItem: chatItem)
    }
    
    func presentError(error: String) {
        viewController?.displayError()
    }
    
    func showLoader() {
        viewController?.showLoader()
    }
    func hideLoader() {
        viewController?.hideLoader()
    }
}
