//
//  RequestCodeInteractor.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/24/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RequestCodeBusinessLogic
{
    func doSomething(request: RequestCode.Something.Request)
}

protocol RequestCodeDataStore
{
    var email: String { get set }
}

class RequestCodeInteractor: RequestCodeBusinessLogic, RequestCodeDataStore
{
    var presenter: RequestCodePresentationLogic?
    var worker: RequestCodeWorker?
    var email: String = ""
    
    // MARK: Do something
    
    func doSomething(request: RequestCode.Something.Request)
    {
        worker = RequestCodeWorker()
        presenter?.showLoader()
        _ = worker?.doRequestCodeWorker(email: request.email,
                                        completion: { response in
                                            if (response.isSuccess) {
                                                self.presenter?.hideLoader()
                                                let response = RequestCode.Something.Response()
                                                self.presenter?.presentSomething(response: response)
                                            }else {
                                                self.presenter?.hideLoader()
                                                self.presenter?.presentError(error: response.errorForUser)
                                            }
        })
    }
}
