//
//  RequestCodeRouter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/24/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RequestCodeRoutingLogic
{
  func routeToSendCode()
}

protocol RequestCodeDataPassing
{
  var dataStore: RequestCodeDataStore? { get set }
}

class RequestCodeRouter: NSObject, RequestCodeRoutingLogic, RequestCodeDataPassing
{
  weak var viewController: RequestCodeViewController?
  var dataStore: RequestCodeDataStore?
  
  // MARK: Routing
  
  func routeToSendCode()
  {
    let destinationVC = Constants.Storyboards.authenticationStoryboard.instantiateViewController(withIdentifier: "SendCodeViewController") as! SendCodeViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSendCode(source: dataStore!, destination: &destinationDS)
      navigateToSendCode(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToSendCode(source: RequestCodeViewController, destination: SendCodeViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSendCode(source: RequestCodeDataStore, destination: inout SendCodeDataStore)
  {
    destination.email = source.email
  }
}
