//
//  RequestCodeViewController.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/24/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RequestCodeDisplayLogic: class
{
    func displaySomething(viewModel: RequestCode.Something.ViewModel)
    func displayError()
    func showLoader()
    func hideLoader()
}

class RequestCodeViewController: UIViewController, RequestCodeDisplayLogic
{
    var interactor: RequestCodeBusinessLogic?
    var router: (NSObjectProtocol & RequestCodeRoutingLogic & RequestCodeDataPassing)?
    
    @IBOutlet weak var requestView: UIView!
    @IBOutlet weak var emailTextField: TitleTextField!
    @IBOutlet weak var requestButton: UIButton!
    @IBOutlet weak var errorLabel: UILabel!
    @IBOutlet weak var bottomConstraint: NSLayoutConstraint!
    @IBOutlet weak var topConstraint: NSLayoutConstraint!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = RequestCodeInteractor()
        let presenter = RequestCodePresenter()
        let router = RequestCodeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        requestButton.activationState(active: false)
        addTargetsTextField()
        hideKeyboardWhenTappedAround()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        requestView.roundCorners(corners: .topRight, radius: 50)
        requestButton.roundCorners(corners:[.topLeft, .bottomLeft], radius: 20.0)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillAppear(notification:)),
                                               name: UIResponder.keyboardWillShowNotification,
                                               object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillDisappear(notification:)),
                                               name: UIResponder.keyboardWillHideNotification,
                                               object: nil)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.removeObserver(self, name: UIResponder.keyboardWillHideNotification , object: nil)
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSendRequest()
    {
        let request = RequestCode.Something.Request(email: emailTextField.text ?? "")
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: RequestCode.Something.ViewModel)
    {
        DispatchQueue.main.async {
            self.router?.dataStore?.email = self.emailTextField.text ?? ""
            self.router?.routeToSendCode()
        }
    }
    
    func displayError() {
        DispatchQueue.main.async {
            self.errorLabel.isHidden = false
        }
    }
    
    //MARK: - Hide & Show Loader
    
    func showLoader() {
        view.showLoader()
    }
    
    func hideLoader() {
        DispatchQueue.main.async {
            self.view.removeLoader()
        }
    }
    
    // MARK: Actions
    @IBAction func backButtonAction(_ sender: Any) {
        navigationController?.popViewController(animated: true)
    }
    
    @IBAction func requestButtonAction(_ sender: Any) {
        doSendRequest()
    }
    
    //MARK: - Target Text Field
    
    func addTargetsTextField() {
        emailTextField.addTarget(self, action: #selector(editingChanged), for: .editingChanged)
    }
    
    @objc func editingChanged(_ textField: UITextField) {
        if textField.text?.count == 1 && textField.text?.first == " " {
            textField.text = ""
            return
        }
        guard
            let emailStr = emailTextField.text, !emailStr.isEmpty
            else {
                requestButton.activationState(active: false)
                return
        }
        requestButton.activationState(active: true)
    }
    
    //    MARK: - Keyboard Show & Hide
    @objc
    func keyboardWillAppear(notification: NSNotification?) {
        
        guard let keyboardFrame = notification?.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue else {
            return
        }
        
        let keyboardHeight: CGFloat
        if #available(iOS 11.0, *) {
            keyboardHeight = keyboardFrame.cgRectValue.height - self.view.safeAreaInsets.bottom
        } else {
            keyboardHeight = keyboardFrame.cgRectValue.height
        }
        
        let deviceModel =  UIDevice().type
        switch deviceModel {
        case  .iPhone5, .iPhone5S, .iPhone5C, .iPhoneSE:
            topConstraint.constant = 100.0
            bottomConstraint.constant = keyboardHeight + 10
        case .iPhoneX, .iPhoneXR, .iPhoneXS, .iPhoneXSMax, .iPhone11, .iPhone11Pro, .iPhone11ProMax:
            bottomConstraint.constant = keyboardHeight + 50
        default:
            bottomConstraint.constant = keyboardHeight + 10
            break
        }
    }
    
    @objc
    func keyboardWillDisappear(notification: NSNotification?) {
        let deviceModel =  UIDevice().type
        switch deviceModel {
        case  .iPhone5, .iPhone5S, .iPhone5C, .iPhoneSE:
            topConstraint.constant = 125
        default:
            break
        }
        bottomConstraint.constant = 61
    }
}

extension RequestCodeViewController : UITextFieldDelegate {
    func textFieldDidBeginEditing(_ textField: UITextField) {
        errorLabel.isHidden = true
    }
}
