//
//  RequestCodePresenter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/24/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RequestCodePresentationLogic
{
    func presentSomething(response: RequestCode.Something.Response)
    func presentError(error: String)
    func showLoader()
    func hideLoader()
}

class RequestCodePresenter: RequestCodePresentationLogic
{
    weak var viewController: RequestCodeDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: RequestCode.Something.Response)
    {
        let viewModel = RequestCode.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentError(error: String) {
        viewController?.displayError()
    }
    
    func showLoader() {
        viewController?.showLoader()
    }
    func hideLoader() {
        viewController?.hideLoader()
    }
}
