//
//  ServicesPresenter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 3/6/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ServicesPresentationLogic
{
    func presentSuccess(orders:[UserOrder])
    func presentError(error: String)
    func showLoader()
    func hideLoader()
}

class ServicesPresenter: ServicesPresentationLogic
{
    weak var viewController: ServicesDisplayLogic?
    
    // MARK: Do something
    
    func presentSuccess(orders:[UserOrder]) {
        viewController?.displayGetUserOrderSuccess(orders: orders)
    }
    
    func presentError(error: String) {
        viewController?.displayError()
    }
    
    func showLoader() {
        viewController?.showLoader()
    }
    func hideLoader() {
        viewController?.hideLoader()
    }
}
