//
//  ServicesRouter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 3/6/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ServicesRoutingLogic
{
    func routeToAllServices()
    func routeToOrderViewController()
    func routeToChat()
}

protocol ServicesDataPassing
{
    var dataStore: ServicesDataStore? { get set }
}

class ServicesRouter: NSObject, ServicesRoutingLogic, ServicesDataPassing
{
    weak var viewController: ServicesViewController?
    var dataStore: ServicesDataStore?
    
    // MARK: Routing
    
    func routeToAllServices() {
        let destinationVC = Constants.Storyboards.servicesStoryboard.instantiateViewController(withIdentifier: "AllServicesViewController") as! AllServicesViewController
        navigateToAllServices(source: viewController!, destination: destinationVC)
    }
    
    func routeToOrderViewController()
    {
        let destinationVC = Constants.Storyboards.servicesStoryboard.instantiateViewController(withIdentifier: "OrderViewController") as! OrderViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToOrderViewController(source: dataStore!, destination: &destinationDS)
        navigateToOrderViewController(source: viewController!, destination: destinationVC)
    }
    
    func routeToChat() {
        let destinationVC = Constants.Storyboards.servicesStoryboard.instantiateViewController(withIdentifier: "ChatViewController") as! ChatViewController
        
        navigateToChat(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: Navigation
    
    func navigateToAllServices(source: ServicesViewController, destination: AllServicesViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToOrderViewController(source: ServicesViewController, destination: OrderViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToChat(source: ServicesViewController, destination: ChatViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToOrderViewController(source: ServicesDataStore, destination: inout OrderDataStore)
    {
        destination.isUserOrder = true
        destination.orderId = source.orderId
    }
}
