//
//  OrderRouter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 3/9/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OrderRoutingLogic
{
  func routeToChat()
}

protocol OrderDataPassing
{
  var dataStore: OrderDataStore? { get }
}

class OrderRouter: NSObject, OrderRoutingLogic, OrderDataPassing
{
  weak var viewController: OrderViewController?
  var dataStore: OrderDataStore?
  
  // MARK: Routing
  
  func routeToChat() {
    let destinationVC = Constants.Storyboards.servicesStoryboard.instantiateViewController(withIdentifier: "ChatViewController") as! ChatViewController

      navigateToChat(source: viewController!, destination: destinationVC)
    }

  // MARK: Navigation
  
  func navigateToChat(source: OrderViewController, destination: ChatViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: OrderDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
