//
//  OrderWorker.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 3/9/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class OrderWorker
{
   func doGetOneOrder(productId: String, completion: (( _ response: ResponseData) -> Void)? ) {
    NetworkManager.requestGetOneOrder(userInfo: ["productId":productId], completion: completion)
     }
    
    func doGetUserOrder(orderId: String, completion: (( _ response: ResponseData) -> Void)? ) {
        NetworkManager.requestGetUserOrder(userInfo: ["orderId":orderId], completion: completion)
    }
    
    func doUploadFile(image: UIImage, completion: (( _ response: ResponseData) -> Void)? ) {
        NetworkManager.requestUploadImnage(image: image, completion: completion)
       }
    
    func doCreateOrder(orderId: String, docIds:[[String:Any]],  completion: (( _ response: ResponseData) -> Void)? ) {
        NetworkManager.requestCreateOrder(userInfo: ["productId":orderId, "documentIds" : docIds], completion: completion)
       }
    
    func doPay(orderId:String, paymentString:String, completion: (( _ response: ResponseData) -> Void)? ) {

        NetworkManager.requestPayment(userInfo: ["paymentData":paymentString, "orderId" : orderId], completion: completion)
    }
}
