//
//  WelcomeRouter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/21/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WelcomeRoutingLogic {
    func routeToLogIn()
    func routeToSignUp()
}

protocol WelcomeDataPassing {
    var dataStore: WelcomeDataStore? { get }
}

class WelcomeRouter: NSObject, WelcomeRoutingLogic, WelcomeDataPassing {
    weak var viewController: WelcomeViewController?
    var dataStore: WelcomeDataStore?
    
    // MARK: Routing
    
    func routeToLogIn() {
        
        let destinationVC = Constants.Storyboards.authenticationStoryboard.instantiateViewController(withIdentifier: "SIgnInViewController") as! SIgnInViewController
        navigateToLogIn(source: viewController!, destination: destinationVC)
    }
    
    func routeToSignUp() {
        
        let destinationVC = Constants.Storyboards.authenticationStoryboard.instantiateViewController(withIdentifier: "SignUpViewController") as! SignUpViewController
        navigateToSignUp(source: viewController!, destination: destinationVC)
    }
    
    
    // MARK: Navigation
    
    func navigateToLogIn(source: WelcomeViewController, destination: SIgnInViewController)
    {
        source.show(destination, sender: nil)
    }
    
    func navigateToSignUp(source: WelcomeViewController, destination: SignUpViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: WelcomeDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
