//
//  WelcomeInteractor.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/21/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeBusinessLogic {
  func doSomething(request: Welcome.Something.Request)
}

protocol WelcomeDataStore {
  //var name: String { get set }
}

class WelcomeInteractor: WelcomeBusinessLogic, WelcomeDataStore {
  var presenter: WelcomePresentationLogic?
  var worker: WelcomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Welcome.Something.Request)
  {
    worker = WelcomeWorker()
    
    let response = Welcome.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
