//
//  WelcomeViewController.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/21/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeDisplayLogic: class
{
    func displaySomething(viewModel: Welcome.Something.ViewModel)
}

class WelcomeViewController: UIViewController, WelcomeDisplayLogic
{
    var interactor: WelcomeBusinessLogic?
    var router: (NSObjectProtocol & WelcomeRoutingLogic & WelcomeDataPassing)?
    
    @IBOutlet weak var signupButtonLeftConstraint: NSLayoutConstraint!
    @IBOutlet weak var loginButtonLeftConstraint: NSLayoutConstraint!
    @IBOutlet weak var logoImage: UIImageView!
    @IBOutlet weak var signUpButton: UIButton!
    @IBOutlet weak var logInButton: UIButton!
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = WelcomeInteractor()
        let presenter = WelcomePresenter()
        let router = WelcomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
        
        UIView.animate(withDuration: 0.3, animations: {
            self.logoImage.isHidden = false
            self.loginButtonLeftConstraint.constant = 16
            self.signupButtonLeftConstraint.constant = 16
            self.view.layoutIfNeeded()
        }, completion:nil)
        
        logInButton.applyGradient(colours: [Constants.Colors.bleuStart,.white], startPoint: CGPoint(x: 0.0, y: 0.5), endPoint:CGPoint(x: 1.0, y: 0.5) )
        
        logInButton.roundCorners(corners:[.topLeft, .bottomLeft], radius: 20.0)
        signUpButton.roundCorners(corners: [.topLeft, .bottomLeft], radius: 20.0)
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = Welcome.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Welcome.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    
    // MARK: Actions
    
    @IBAction func loginButtonAction(_ sender: UIButton) {
        router?.routeToLogIn()
    }
    @IBAction func signUpButtonAction(_ sender: Any) {
        router?.routeToSignUp()
    }
}
