//
//  WelcomePresenter.swift
//  Firstngo
//
//  Created by Artash Ghazaryan on 2/21/20.
//  Copyright (c) 2020 Artash Ghazaryan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomePresentationLogic
{
  func presentSomething(response: Welcome.Something.Response)
}

class WelcomePresenter: WelcomePresentationLogic
{
  weak var viewController: WelcomeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Welcome.Something.Response)
  {
    let viewModel = Welcome.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
